version: '2'
services:
  web:
    build: ./web
    ports:
     - "5000:5000"
    volumes:
     - /data:/data
     - /scratch:/scratch
     - /home:/home
    environment:
      - DEBUG=FALSE

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
