LDAP_USER = "cn=USER,dc=SOMEDOMAIN,dc=COM"
LDAP_KEY = "SUPERSECRETCOMPLEXTPASSWORD_1"

BASIC_AUTH_USERNAME = "A NAME"
BASIC_AUTH_PASSWORD = "SUPERSECRETCOMPLEXTPASSWORD_2"

GMAIL_USERNAME = "EMAIL@GMAIL.COM"
GMAIL_PASSWORD = "SUPERSECRETCOMPLEXTPASSWORD_3"
